name: PgmRegions
main: org.m2k.PgmRegions
version: 1.0
api-version: 1.8
description: A simple plugin to select points like WorldEdit and create PGM XML regions.
softdepend: [WorldEdit]
website: https://github.com/Mew2K/PgmRegions

commands:
  pwand:
    description: Gives the player a stone axe for region selection.
    usage: /pwand
    aliases: [pw, /pwand, /pw]
    permission: pgmregions.pwand
    permission-message: "You do not have access to this command."
  pregion:
    description: Converts selected points to PGM XML coordinates.
    usage: /pregion
    aliases: [pr, /pregion, /pr]
    permission: pgmregions.pregion
    permission-message: "You do not have access to this command."